(function () {
  const SHIP_MODELS = {
    scout: {
      id: "scout",
      name: "Scout",
      role: "Allrounder",
      maxHp: 3,
      maxArmor: 2,
      speed: 1,
      critChance: 0.1,
      critDamage: 1.5,
      reloadRate: 1,
      physicalDamage: 1,
      energyDamage: 1,
      explosiveDamage: 1,
      heatDamage: 1,
      xpBonus: 1,
      shieldRechargeMult: 1,
      drillRechargeMult: 1,
      rocketCooldownMult: 1,
      startShield: false,
      startLaser: false,
      startRocket: false,
      startDrill: false,
      startPlasma: false,
      colorA: "#71f4ff",
      colorB: "#ff995a",
    },
    tank: {
      id: "tank",
      name: "Bulwark",
      role: "Tank",
      maxHp: 5,
      maxArmor: 5,
      speed: 0.82,
      critChance: 0.06,
      critDamage: 1.4,
      reloadRate: 0.9,
      physicalDamage: 1.08,
      energyDamage: 0.9,
      explosiveDamage: 1,
      heatDamage: 0.9,
      xpBonus: 0.95,
      shieldRechargeMult: 1,
      drillRechargeMult: 0.86,
      rocketCooldownMult: 1,
      startShield: false,
      startLaser: false,
      startRocket: false,
      startDrill: true,
      startPlasma: false,
      colorA: "#6db5ff",
      colorB: "#8bd2ff",
    },
    glass: {
      id: "glass",
      name: "Viper",
      role: "Glaskanone",
      maxHp: 2,
      maxArmor: 1,
      speed: 1.2,
      critChance: 0.22,
      critDamage: 1.8,
      reloadRate: 1.1,
      physicalDamage: 0.95,
      energyDamage: 1.22,
      explosiveDamage: 1,
      heatDamage: 1.05,
      xpBonus: 1.1,
      shieldRechargeMult: 1,
      drillRechargeMult: 1,
      rocketCooldownMult: 1,
      startShield: false,
      startLaser: true,
      startRocket: false,
      startDrill: false,
      startPlasma: false,
      colorA: "#ff8f8f",
      colorB: "#ffc06f",
    },
    aegis: {
      id: "aegis",
      name: "Aegis",
      role: "Schild-Experte",
      maxHp: 3,
      maxArmor: 3,
      speed: 0.95,
      critChance: 0.1,
      critDamage: 1.5,
      reloadRate: 1,
      physicalDamage: 1,
      energyDamage: 1.06,
      explosiveDamage: 0.95,
      heatDamage: 1,
      xpBonus: 1,
      shieldRechargeMult: 0.72,
      drillRechargeMult: 1,
      rocketCooldownMult: 1,
      startShield: true,
      startLaser: false,
      startRocket: false,
      startDrill: false,
      startPlasma: false,
      startCannonHalf: true,
      colorA: "#7ee6d0",
      colorB: "#b7fff0",
    },
    demolisher: {
      id: "demolisher",
      name: "Demolisher",
      role: "Raketenboot",
      maxHp: 3,
      maxArmor: 2,
      speed: 0.92,
      critChance: 0.09,
      critDamage: 1.55,
      reloadRate: 0.95,
      physicalDamage: 0.95,
      energyDamage: 0.9,
      explosiveDamage: 1.22,
      heatDamage: 0.95,
      xpBonus: 1,
      shieldRechargeMult: 1,
      drillRechargeMult: 1,
      rocketCooldownMult: 0.78,
      startShield: false,
      startLaser: false,
      startRocket: true,
      startDrill: false,
      startPlasma: false,
      colorA: "#ffad66",
      colorB: "#ffd7a7",
    },
    pioneer: {
      id: "pioneer",
      name: "Pioneer",
      role: "Bohrer-Pilot",
      maxHp: 4,
      maxArmor: 3,
      speed: 1.02,
      critChance: 0.11,
      critDamage: 1.55,
      reloadRate: 1,
      physicalDamage: 1.06,
      energyDamage: 1,
      explosiveDamage: 0.95,
      heatDamage: 1.05,
      xpBonus: 1,
      shieldRechargeMult: 1,
      drillRechargeMult: 0.78,
      rocketCooldownMult: 1,
      startShield: false,
      startLaser: false,
      startRocket: false,
      startDrill: true,
      startPlasma: false,
      colorA: "#9cc2ff",
      colorB: "#e7f0ff",
    },
    pyre: {
      id: "pyre",
      name: "Pyre",
      role: "Plasmawerfer",
      maxHp: 3,
      maxArmor: 2,
      speed: 1.04,
      critChance: 0.1,
      critDamage: 1.45,
      reloadRate: 1,
      physicalDamage: 0.9,
      energyDamage: 0.95,
      explosiveDamage: 0.95,
      heatDamage: 1.26,
      xpBonus: 1,
      shieldRechargeMult: 1,
      drillRechargeMult: 1,
      rocketCooldownMult: 1,
      startShield: false,
      startLaser: false,
      startRocket: false,
      startDrill: false,
      startPlasma: true,
      colorA: "#ff8c6a",
      colorB: "#ffd2a6",
    },
  };

  const DIFFICULTY_MODES = {
    easy: {
      id: "easy",
      title: "Einfach",
      description: "Langsamere Gegner, weniger Spawn-Druck, +50% Schiff-HP.",
      playerHpMult: 1.5,
      objectSpeedMult: 0.78,
      edgeSpeedMult: 0.82,
      enemyProjectileSpeedMult: 0.86,
      bossHpMult: 0.86,
      spawnRateMult: 0.86,
      edgeSpawnRateMult: 0.9,
      bossAggroMult: 0.86,
    },
    medium: {
      id: "medium",
      title: "Mittel",
      description: "Empfohlene Standardwerte.",
      playerHpMult: 1,
      objectSpeedMult: 1,
      edgeSpeedMult: 1,
      enemyProjectileSpeedMult: 1,
      bossHpMult: 1,
      spawnRateMult: 1,
      edgeSpawnRateMult: 1,
      bossAggroMult: 1,
    },
    hard: {
      id: "hard",
      title: "Schwierig",
      description: "Schnellere Gegner, dichterer Spawn, haertere Bosse.",
      playerHpMult: 0.85,
      objectSpeedMult: 1.2,
      edgeSpeedMult: 1.18,
      enemyProjectileSpeedMult: 1.18,
      bossHpMult: 1.24,
      spawnRateMult: 1.18,
      edgeSpawnRateMult: 1.14,
      bossAggroMult: 1.18,
    },
  };

  window.VoidConfig = {
    SHIP_MODELS,
    DIFFICULTY_MODES,
  };
})();
